version: '3'
services:
    db:
     container_name: 'mysql2'
     image: mysql:5.7
     environment:
      MYSQL_DATABASE: 'milab_beta'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
     volumes:
      - msdata:/var/lib/mysql
    
    web:
     build: .
     command: bash -c "python mysite/manage.py runserver 0.0.0.0:8081"
     ports:
      - "80:8081"
     volumes:
      - ./:/django-files
     depends_on:
      - db
volumes:
    msdata:
